{{- if .Values.thanosSidecar.tlsServer.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ template "prometheus.server.fullname" . }}-thanos-sidecar-tls-server
data:
  server.crt: {{ .Values.thanosSidecar.tlsServer.crt }}
  server.key: {{ .Values.thanosSidecar.tlsServer.key }}
  ca.crt: {{ .Values.thanosSidecar.tlsServer.ca }}
{{- end -}}
