{{- if .Values.thanosSidecar.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.server.fullname" . }}-thanos-sidecar-http
{{- if .Values.thanosSidecar.httpService.annotations }}
  annotations:
{{ toYaml .Values.thanosSidecar.httpService.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.thanosSidecar.httpService.type }}
  {{- if .Values.thanosSidecar.httpService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.thanosSidecar.httpService.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 10902
      targetPort: http
      {{- if .Values.thanosSidecar.httpService.nodePortEnabled }}
      nodePort: {{ .Values.thanosSidecar.service.httpNodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus.server.matchLabels" . | nindent 4 }}
{{- end -}}
